[package]
name = "kactus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.29", features = ["full"] }
futures = "0.3.28"
reqwest = "0.11"
redis = "0.23"
csv = "1.2"
hyper = { version = "1.0.0-rc.3", features = ["full"] }
http-body-util = "0.1.0-rc.3"
termion = "*"
farmhash = "1.1"
rand = "0.8"
actix-web = "4"
qstring = "0.7"
protobuf-json-mapping = "3.2.0"
protobuf = { version = "3.2.0", features = ["with-bytes"] }
gtfs-rt = "0.3"
serde_derive = "*"
serde_json = "*"
serde = "*"
arguments = "0.7"

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "testcachetime"
path = "src/test-cache-time/main.rs"

[[bin]]
name = "testm"
path = "src/testm/testm.rs"

[[bin]]
name = "ingestv2"
path = "src/ingestv2/main.rs"

[[bin]]
name = "ingestmetrolink"
path = "src/ingestv2/metrolink.rs"